Add Chinese translation
Levminer/authme pull request #303
Opened 2024-06-19 03:11 UTC by pedoc

# Reference issue

- #258

## Purpose

-   Added Chinese translation

## Approach

## TODO

-   [x] Read [Contributing](https://github.com/Levminer/authme/blob/main/.github/CONTRIBUTING.md)
-   [x] Read [Code of conduct](https://github.com/Levminer/authme/blob/main/.github/CODE_OF_CONDUCT.md)
-   [x] Run `npm run lint`

2024-06-23 15:09 UTC, Levminer requested changes
Thanks for your work! Please fix the 2 issues I commented on.

2024-06-23 15:09 UTC, Levminer commented on interface/utils/language/zh.ts
> +export const localeEN = {
This should be localeZH

2024-06-23 15:09 UTC, Levminer commented on interface/utils/language/zh.ts
> +		googleAuthTutorial: ["从 Google Authenticato 导出2FA 代码: 点击屏幕左上角的菜单:转移账户->导出账户", "从屏幕截图并保存二维码,或者如果你使用的是 Android 手机,可以用另一部手机拍照.将这些照片传输到你的电脑上", "进入 Authme 的 导入 页面: 侧边栏 -> 导入", "单击“选择图片”按钮，然后选择从手机传输的图片"]
Missed an "a" Google Authentico

2024-06-24 01:42 UTC, pedoc commented
The problem has been solved, please check

2024-06-24 09:59 UTC, Levminer approved these changes
Thanks!

2024-06-24 10:00 UTC, merged