Add clear data options
Levminer/authme pull request #315
Opened 2024-08-25 17:31 UTC by valentinb102

# Reference issue

-   #311 

## Purpose

-   Added 2 options so user can clear just the codes or everything.
-   Reused toggles as checkboxes.

## Approach

-   Combined clear codes function with clear data function using 2 bools. 
-   Is this the right approach? 
-   How should I clear just the settings without clearing codes?

2024-08-26 08:09 UTC, Levminer commented
Thanks for your work so far!

1. The toggles are fine but they should be in a dialog (example: https://github.com/Levminer/authme/blob/dfdf7b0bbd11233814153c57c082473996229f54/interface/windows/import/index.ts#L84 and https://github.com/Levminer/authme/blob/dfdf7b0bbd11233814153c57c082473996229f54/interface/windows/import/import.svelte#L226)

2. You can clear only the codes like this: https://github.com/Levminer/authme/blob/dfdf7b0bbd11233814153c57c082473996229f54/interface/windows/settings/index.ts#L75

2024-08-26 15:46 UTC, valentinb102 commented
How should I clear just the settings? I guess that would be everything excluding codes and the password?

2024-08-29 08:53 UTC, Levminer commented
Yes, you can set settings.settings to 

```ts
{
		language: 0,
		launchOnStartup: true,
		minimizeToTray: true,
		optionalAnalytics: true,
		codesDescription: false,
		blurCodes: false,
		sortCodes: 0,
		codesLayout: 0,	
},
```

2024-08-29 19:08 UTC, valentinb102 commented
Should the four warning strings be moved into the localization file?

https://github.com/Levminer/authme/blob/a2c1c0986ac1610e935aeedbe9828bc33e6ce528/interface/windows/settings/index.ts#L55
https://github.com/Levminer/authme/blob/a2c1c0986ac1610e935aeedbe9828bc33e6ce528/interface/windows/settings/index.ts#L70
https://github.com/Levminer/authme/blob/a2c1c0986ac1610e935aeedbe9828bc33e6ce528/interface/windows/settings/index.ts#L92
https://github.com/Levminer/authme/blob/a2c1c0986ac1610e935aeedbe9828bc33e6ce528/interface/windows/settings/index.ts#L98

2024-08-30 08:57 UTC, Levminer commented
Its' not necessary.

2024-08-30 20:09 UTC, valentinb102 commented
So is this PR good to go? I think I added everything.

2024-08-30 22:50 UTC, Levminer requested changes
Fix the formatting and good to go! Thanks!

2024-08-30 22:50 UTC, Levminer commented on interface/windows/settings/index.ts
> +		setSettings(settings)
Fix formatting

2024-08-31 17:08 UTC, Levminer approved these changes

2024-09-01 09:28 UTC, merged